version: "2"

services:
  entrypoint:
    build: ./entrypoint
    image: entrypoint
  vote:
    build: ./vote
    image: bfirsh/serverless-vote

  result:
    build: ./result
    image: bfirsh/serverless-result

  record-vote-task:
    build: ./record-vote-task
    image: bfirsh/serverless-record-vote-task
