version: '2'

services:
  entrypoint:
    build: entrypoint
    image: entrypoint
    ports:
      - 80:80
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "$DOCKER_CERT_PATH:$DOCKER_CERT_PATH"
    environment:
      - DOCKER_HOST
      - DOCKER_MACHINE_NAME
      - DOCKER_TLS_VERIFY
      - DOCKER_CERT_PATH
  db:
    image: postgres:9.4
